### ISSUE TITLE
insert data in specific cell

### ISSUE THREAD

**Issue by ademir10** [caxlsx/axlsx_rails#105]
Hi Guys! how are you?
I'd like to insert two 'each do' results, side by side in my worksheet, it's possible?
For example:
| TABLE A CONTENT | | TABLE B CONTENT |
The first data start in cell A1 and go until cell E2 and between this two cells we gonna have all content.

At right side i'd like to insert another data table result, starting in cell G2, but i don't know how to do.
Any suggestion? thanks!

**Comment by straydogstudio** [comment]
@ademir10 You've not gotten any response here. This sounds like an Axlsx problem, not an axlsx_rails problem. Did you submit it somewhere else?
