### ISSUE TITLE
rails 4 bundle error

### ISSUE THREAD

**Issue by chabgood** [caxlsx/axlsx_rails#115]
NoMethodError: undefined method `spec' for nil:NilClass
An error occurred while installing axlsx (2.1.0.pre), and Bundler cannot continue.

Gemfile portion:
gem 'rubyzip', '>= 1.2.1'
gem 'axlsx', git: 'https://github.com/randym/axlsx.git', ref: 'c8ac844'
gem 'axlsx_rails'

**Comment by straydogstudio** [comment]
@chabgood Which version of axlsx_rails did this define?

**Comment by chabgood** [comment]
Right now I have no idea but the ref is here, 'c8ac844'

**Comment by straydogstudio** [comment]
Consider the latest release of axlsx_rails at http://github.com/caxlsx/axlsx_rails, which now depends on the new community Axlsx release at http://github.com/caxlsx/caxlsx
