### ISSUE TITLE
Remove dependency on straydogstudio fork of acts_as_xlsx

### ISSUE THREAD

**Issue by OpenCoderX** [caxlsx/axlsx_rails#123]
`gem 'acts_as_xlsx', git: 'https://github.com/straydogstudio/acts_as_xlsx.git'`

**Comment by straydogstudio** [comment]
@OpenCoderX Good catch. Changed. It will change again when I get to releasing a new version of acts_as_xlsx as acts_as_caxlsx which depends on caxlsx. But this particular line is only used in testing.
