### ISSUE TITLE
Export template with mapped columns?

### ISSUE THREAD

**Issue by billy-whizz** [caxlsx/axlsx_rails#125]
First, thanks for this awesome awesome gem. 
I have successfully implemented data validations in the exported template. I now want to go a step further and export the same template with some columns mapped to each other. For example, If a user selects a country from the country dropdown in the template, the code column should be automatically populated, preventing the user from having to do anything in that column.
Any ideas would be appreciated, thank you!

**Comment by OpenCoderX** [comment]
The first formulas that come to mind are VLOOKUP or INDIRECT, I don't think the gem has an abstraction for dependent column population.
