### ISSUE TITLE
can i use background job to generate rows in the Excel file and download it later?

### ISSUE THREAD

**Issue by vonchristian** [caxlsx/axlsx_rails#131]

**Comment by vonchristian** [comment]
Server times out because of large amounts of data being exported. I need help on how to use background job for exporting data to Excel. Thank you.

**Comment by OpenCoderX** [comment]
You can use Sidekiq, https://github.com/mperham/sidekiq, to manage the background jobs and Rails ActiveStorage to persist the files and genrate download links: https://guides.rubyonrails.org/active_storage_overview.html.

**Comment by OpenCoderX** [comment]
I'm closing this as it is not related to a problem with the gem.

**Comment by straydogstudio** [comment]
@vonchristian If you run into issues getting templates to work inside Sidekiq, see the readme for running the gem in scripts.
